---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    - namespace="robertdebock/"
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-centos-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - namespace="opensuse/" image="leap"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "iRWR2TQTAdiM4jhhL9bWST7Jn1EcRL1IL+i42a5WZtVV+zGukj5KULHJq+U+MsDLLux23pw/9GQ7UJ8ATOWwRXjJws8vxZADAI/KPiJpTY366V/TjH1MlKfOrK0g630FrlMSADxprVtuq+71nFEaZT29/9DgqUbEw0uyf08DThbHrAE2WJYSSkcHlbUUtMnKT7jaBx8NgZxA6BkmvdWMhGMZ5Tz4O7faLlwxuGjXDCvZ6usmQyA3CBb3X85sNtccrnIHZw8CaYU97vxFCmlxIkrbaj1Rrt3b77Q9s41M1c0au7ZWWmd8zJZm9EmmiM1faJZuxjWKAO0Ylaby7nRRoW7lzgY04HlcsFT5fnql7QB71CTwxZyhlzO7dBz7bdVro7OMVTq2APzfDebeewLL79GRmsDRYutZXsRR0t06rm0eY1MxDl9WmDgWLLCDyLT69cFyuPoUT+Npnc5FCUz0FWD/QadWuataUWiPLGXXpEeUazKa94+D2QOUm6/KrKO211jD8/y57J9uR6+6BJl3p39o0EAG8CP3T+90chOsNz5ixMFgfrTN+DfFl9oLWhznVyYx0e87fFdq+lMgiwT6Z6VXVU4niQk0ZtQEy5fhizG0jXWcsBEBMD3XvRyJAeNPONVXA1JCS/gJ757dYXMShIo1dd3YTop5kHLvMW2+Eo4="
  email: false
